### ISSUE TITLE
关闭内核自带ai时(mob-ai=off),原版生物(Human除外)无法观测到其移动

### ISSUE THREAD

**Issue by Antique233** [MemoriesOfTime/NukkitPetteriM1Edition#10]
视频1与视频2套用的为同一ai,ai令生物移动使用的是Entity中的move函数
视频1中human实体可以正常移动
而视频2中zombie实体(其他原版生物如狗等也是如此)看起来不移动,实际上位置发生了变化但玩家无法看见
视频1:
https://user-images.githubusercontent.com/21009992/219556906-ef046143-18db-4724-a5cc-cc25ad715874.mp4
视频2:
https://user-images.githubusercontent.com/21009992/219557104-0719f6c2-61df-479e-9a16-8675f5ee6a30.mp4

**Comment by lt-name** [comment]
已确认原因是 关闭实体ai后会关闭实体大部分移动处理

**Comment by Nissining** [comment]
可能已经修复，具体还需进一步测试

**Comment by lt-name** [comment]
已在PR#24尝试修复，此issue暂时关闭，如有问题请重新打开

**Comment by Antique233** [comment]
版本master/7e2ed33(刚刚更新的)
经测试关闭ai的情况下问题仍然存在

**Comment by lt-name** [comment]
麻烦有时间再测试下最新版

**Comment by Antique233** [comment]
可以正常使用了,感谢修复
