### ISSUE TITLE
一些内核中已有的方块无法使用

### ISSUE THREAD

**Issue by Antique233** [MemoriesOfTime/NukkitPetteriM1Edition#25]
一些内核中已有的方块无法使用
例如莲叶(BlockWaterLily),灯笼(BlockLantern)无法被放置
详见下面的视频,从视频中可以看出我没有装任何插件且放置方块的地方保证是没有问题,可以正常放置方块的

https://user-images.githubusercontent.com/21009992/220489965-219c0dd4-e056-4148-917f-9166e74b310b.mp4

**Comment by Antique233** [comment]
根据Minecraft wiki上的资料,灯笼于基岩版1.9.0加入(https://minecraft.fandom.com/zh/wiki/%E7%81%AF%E7%AC%BC
睡莲于0.9.0就已加入(https://minecraft.fandom.com/zh/wiki/%E7%9D%A1%E8%8E%B2
考虑到本内核多版本兼容的特性(1.2.0到最新版本),睡莲也总该支持吧orz

**Comment by lt-name** [comment]
灯 因为地图格式限制，id255以上的方块暂时无法放置
睡莲等待确认

**Comment by lt-name** [comment]
睡莲已修复

**Comment by lt-name** [comment]
如果要使用灯笼，请在配置文件中设置multiversion-min-protocol=388
