### ISSUE TITLE
钓鱼竿优化问题

### ISSUE THREAD

**Issue by Antique233** [MemoriesOfTime/NukkitPetteriM1Edition#26]
视角过低时,钓鱼竿无法抛出鱼钩
抛出鱼钩后,若视角过低,无法将上钩的鱼钓上

**Comment by lt-name** [comment]
麻烦录制下复现视频

**Comment by Antique233** [comment]
视频中分别演示了:
1.视角过低无法抛出鱼钩与正常抛出鱼钩
2.正常将鱼钓出与视角过低时无法正常将鱼钓出

https://user-images.githubusercontent.com/21009992/220621246-6963e870-09ac-4d7e-8cb4-38af04e72f65.mp4

**Comment by lt-name** [comment]
麻烦提供下使用的核心版本

**Comment by Antique233** [comment]
![QQ截图20230222214157](https://user-images.githubusercontent.com/21009992/220636885-0a69d23f-1c66-4b62-90b1-bae21f41c1ca.png)

**Comment by lt-name** [comment]
在服务器master/7245744 客户端1.19.62无法复现
麻烦在服务器输入/ver并截图，另外提供下客户端版本

**Comment by Antique233** [comment]
客户端版本1.19.62
https://user-images.githubusercontent.com/21009992/220810911-ec48abd0-6e77-48d9-82d1-9f4371cc6785.mp4

**Comment by Antique233** [comment]
非常抱歉,我尝试卸载了我装在服务器上的插件后再次测试后便不再出现我所描述的bug了
给您添麻烦了!
