### ISSUE TITLE
要求添加版权信息

### ISSUE THREAD

**Issue by CoolLoong** [MemoriesOfTime/NukkitPetteriM1Edition#27]
EntitySlenderProjectile是来自PNX的代码，要求添加版权信息

**Comment by CoolLoong** [comment]
请在EntitySlenderProjectile开头标明代码来源

**Comment by lt-name** [comment]
这部分是从pnx复制过来的，在提交信息说了，但是代码部分pnx那边没标，我这边复制后也忘改了

**Comment by lt-name** [comment]
等我晚上有空加上

**Comment by lt-name** [comment]
已添加
