### ISSUE TITLE
Smithing table

### ISSUE THREAD

**Issue by BlusteryS** [MemoriesOfTime/NukkitPetteriM1Edition#40]
Please add smithing table support from pnx 
https://github.com/PowerNukkitX/PowerNukkitX/commit/b4edc6631cecfd8e71f75fd1a6cce7c8f046a19f
https://github.com/PowerNukkitX/PowerNukkitX/commit/0afdf998f038168c724bdc4465f683f8acf62a21

**Comment by BlusteryS** [comment]
I can commit some code for smithing table, but I don't know why the sections in the SmithingInventory are replacing with air on transaction

**Comment by lt-name** [comment]
> I can commit some code for smithing table, but I don't know why the sections in the SmithingInventory are replacing with air on transaction

I don't understand what you mean, can you elaborate?

**Comment by BlusteryS** [comment]
I can create a pull request with a code for smithing table, but on inventory transaction the slots in the smithing inventory are replacing with air, I don't know why
