### ISSUE TITLE
Hostile mobs

### ISSUE THREAD

**Issue by BlusteryS** [MemoriesOfTime/NukkitPetteriM1Edition#56]
# Bug
Hostile mobs do not attack players.
After damage, they fly away in the direction of the player.

## Video
https://youtu.be/37cghMQLob8

# Nukkit version
![image](https://user-images.githubusercontent.com/52814854/227702985-27dc5322-4104-4280-b897-083037139476.png)

**Comment by lt-name** [comment]
Please update to the latest version for testing

**Comment by BlusteryS** [comment]
Some bugs are still exists [youtu.be/Entd4wxriB4](https://youtu.be/Entd4wxriB4)

- When I get close to a mob it freezes
- When I get close to the creeper, he runs away from me, and starts to follow me only when hit

**Comment by lt-name** [comment]
https://github.com/MemoriesOfTime/NukkitPetteriM1Edition/commit/3d8ed05c073c7c0ddd940c6fe8a3232606acec75
A fix has been attempted in this commit

**Comment by BlusteryS** [comment]
Fixed, thanks
