### ISSUE TITLE
最新版无法自定义物品

### ISSUE THREAD

**Issue by Antique233** [MemoriesOfTime/NukkitPetteriM1Edition#57]
更新前可以正常自定义物品
版本:
![QQ截图20230325214547](https://user-images.githubusercontent.com/21009992/227721156-0868ba82-7deb-490a-a790-c60bc5a9957e.png)
更新后无法正常自定义物品了
![QQ截图20230325214556](https://user-images.githubusercontent.com/21009992/227721172-15a0581c-191b-47ac-ae7e-20496fc02f9e.png)
报错处代码:
![QQ截图20230325214618](https://user-images.githubusercontent.com/21009992/227721175-1edc9ab9-abfb-4383-bb9d-3f1daf94cdab.png)

**Comment by Antique233** [comment]
Item0:
![QQ截图20230325215001](https://user-images.githubusercontent.com/21009992/227721234-17dd1a8e-67fa-4ca4-a89d-4e7c4267cd73.png)

**Comment by lt-name** [comment]
已修复
