### ISSUE TITLE
一些基本的问题

### ISSUE THREAD

**Issue by CoolMagic233** [MemoriesOfTime/NukkitPetteriM1Edition#58]
运行版本:
![image](https://user-images.githubusercontent.com/91107923/229322200-0aeb7afb-ea57-45cb-b744-705ea9f7321d.png)
遇到的问题：
1.空地图或者空的定位地图生成之后地图是透明的(基本的)
2.通过沉船补丁插件生成的箱子，如果玩家拾取到了箱子内的藏宝图，会使客户端直接崩溃(致命的)
3.侦测器方向无论怎么放置都只有一个方向，在我的环境中测试，侦测器无法激活(基本的)

**Comment by lt-name** [comment]
1和2已尝试修复
3侦测器暂未实现功能
