### ISSUE TITLE
Log block cannot be placed in 1.19.81

### ISSUE THREAD

**Issue by BlusteryS** [MemoriesOfTime/NukkitPetteriM1Edition#66]
Log block cannot be placed in 1.19.81
![image](https://user-images.githubusercontent.com/52814854/236303043-b3e17209-9342-41b5-b0fd-67ade42d4e6f.png)

**Comment by lt-name** [comment]
Fixed in https://github.com/MemoriesOfTime/NukkitPetteriM1Edition/commit/3c6ff41a6c3905a0392dce320175103ad0c89816
