### ISSUE TITLE
更新到最新版后自定义物品报错

### ISSUE THREAD

**Issue by Antique233** [MemoriesOfTime/NukkitPetteriM1Edition#86]
上个使用版本:057eb70a55ffccac3f9b7338b1ecf271ba8ebcd4
目前使用版本:e9d70ba3f0402093382c9fb4dbca51d1a427e531

我自定义的物品可以正常被添加入背包
![image](https://github.com/MemoriesOfTime/NukkitPetteriM1Edition/assets/21009992/5d6a656a-5667-4623-9019-4b35c36935e9)
(第一个是我自定义的物品,名称为item0,第二个是我没有自定义的物品,都是可以被正常添加的)
![image](https://github.com/MemoriesOfTime/NukkitPetteriM1Edition/assets/21009992/331130a7-b89c-49b8-a94d-0a36f5018133)
然后报错了,并且自定义材质无法被正常加载
![image](https://github.com/MemoriesOfTime/NukkitPetteriM1Edition/assets/21009992/f49faba9-d854-4860-9699-efe98b5b1b17)

**Comment by lt-name** [comment]
使用的CustomItemAPI？等插件更新

**Comment by Antique233** [comment]
> 使用的CustomItemAPI？等插件更新

直接调用内核里面的这个
![image](https://github.com/MemoriesOfTime/NukkitPetteriM1Edition/assets/21009992/4af57759-ec11-428c-8218-d5724689bfc1)

![image](https://github.com/MemoriesOfTime/NukkitPetteriM1Edition/assets/21009992/2385e7d3-f867-4157-998e-89b6059b39ae)

Item0.java:
![image](https://github.com/MemoriesOfTime/NukkitPetteriM1Edition/assets/21009992/463699f1-edb4-4eb9-8e82-0eb1ae0dacaa)

**Comment by Antique233** [comment]
@lt-name

**Comment by lt-name** [comment]
一会修

**Comment by Antique233** [comment]
好的哥

**Comment by lt-name** [comment]
已修复，请更新到最新构建测试

**Comment by Antique233** [comment]
![image](https://github.com/MemoriesOfTime/NukkitPetteriM1Edition/assets/21009992/e5240b8d-a563-4503-8cbe-84cc6838e3ef)
添加自定义物品时报错
我尝试将配置里的multiversion-min-protocol改成594和595,还是报这个错
运行版本:
![image](https://github.com/MemoriesOfTime/NukkitPetteriM1Edition/assets/21009992/1acc790b-6508-405b-9a5b-33eb10120555)
@lt-name

**Comment by lt-name** [comment]
> ![image](https://user-images.githubusercontent.com/21009992/253345196-e5240b8d-a563-4503-8cbe-84cc6838e3ef.png) 添加自定义物品时报错 我尝试将配置里的multiversion-min-protocol改成594和595,还是报这个错 运行版本: ![image](https://user-images.githubusercontent.com/21009992/253345430-1acc790b-6508-405b-9a5b-33eb10120555.png) @lt-name

已修复
