### ISSUE TITLE
Drop from the Respawn Anchor

### ISSUE THREAD

**Issue by BlusteryS** [MemoriesOfTime/NukkitPetteriM1Edition#91]
If you place and break the anchor, an unknown block will drop
![image](https://github.com/MemoriesOfTime/NukkitPetteriM1Edition/assets/52814854/22b0d5ae-7d48-45dc-a2dd-a7c69a2a7aa0)

**Comment by lt-name** [comment]
Fixed, please update to the latest version for testing
