### ISSUE TITLE
不死图腾的bug

### ISSUE THREAD

**Issue by Antique233** [MemoriesOfTime/NukkitPetteriM1Edition#93]
使用版本:master/9e1398d
副手手持不死图腾时,被setHealth(0)时会进入假死状态,即无敌且不能在聊天栏打字
复现方法:副手手持不死图腾,然后/kill

**Comment by lt-name** [comment]
不死图腾无法避免由/kill命令或虚空伤害造成的死亡
另外我这里测试不会进入假死状态
