### ISSUE TITLE
生物ai关闭后的一些问题

### ISSUE THREAD

**Issue by Antique233** [MemoriesOfTime/NukkitPetteriM1Edition#94]
mob-ai调为off后,一些生物仍具有**部分**ai
如凋零,恼鬼等能够飞行的生物仍然会飞
凋零会爆炸且优先级较高
`
    @EventHandler
    public void onExplosion(ExplosionPrimeEvent event) {
        event.setBlockBreaking(false);
    }
`
尝试在插件中加入以下代码后仍无法阻止凋零的爆炸破坏方块

**Comment by lt-name** [comment]
凋零属于实体
可以尝试监听EntityExplosionPrimeEvent或者EntityExplodeEvent阻止爆炸破坏方块
