### ISSUE TITLE
卡箱子bug

### ISSUE THREAD

**Issue by Antique233** [MemoriesOfTime/NukkitPetteriM1Edition#95]
在打开箱子的一瞬间按下tab打开背包可以进入卡箱子状态
见视频:
https://github.com/MemoriesOfTime/NukkitPetteriM1Edition/assets/21009992/1c81eff3-2b3f-420f-94f9-f32a40142e63

破坏打开的箱子也无法恢复,且此时不再可打开背包
后面开的箱子就全都只有打开的动画但没有实际打开
只有退出服务器重进才能得以恢复

**Comment by BlusteryS** [comment]
I think it's a game bug

**Comment by Antique233** [comment]
> I think it's a game bug

in offline game this bug can't be reproduce
I think it might be caused by the delay between server and player's client

**Comment by Antique233** [comment]
> I think it's a game bug

can you suggest me some method to fix this bug in my plugin
my chest plugin will went wrong if some player use this bug! orz
it may be better if we can add something in MOT to deal with this bug

**Comment by lt-name** [comment]
https://ci.lanink.cn/view/Nukkit/job/Nukkit-MOT-Pipeline/job/dev%252Finv_test/

用这个分支测试

**Comment by Antique233** [comment]
@lt-name 这个分支不会出现这个bug了
